[green_agent]
agentbeats_id = "019bc007-f901-7c10-83f9-c3179191b534"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "solver"
env = {}

[config]
# Add your assessment config here
instance_id = sympy__sympy-20916
# Optional filters:
# instance_id = "django__django-11099"  # Specific task
# repo = "django/django"                 # Filter by repo
# difficulty = "easy"                    # Filter by difficulty