[green_agent]
agentbeats_id = "019bc007-f901-7c10-83f9-c3179191b534"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "assistant"
env = {}

[config]
# Add your assessment config here
